title: AI course
tagline: capstone project
author:
  name: tseng wei
  url: https://www.facebook.com/profile.php?id=100005314030843
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

paginate: 3

tags_path: /tags/
categories_path: /categories/

remote_theme: zivong/jekyll-theme-hydure
#theme: jekyll-theme-hydure
